//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbsys.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ITDBSYS31Entities : DbContext
    {
        public ITDBSYS31Entities()
            : base("name=ITDBSYS31Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<USER_ACCOUNT> USER_ACCOUNT { get; set; }
        public DbSet<vw_all_user_account> vw_all_user_account { get; set; }
    
        public virtual ObjectResult<sp_getUserById_Result> sp_getUserById(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getUserById_Result>("sp_getUserById", useridParameter);
        }
    
        public virtual int sp_new_useraccount(string userUname, string userPword)
        {
            var userUnameParameter = userUname != null ?
                new ObjectParameter("userUname", userUname) :
                new ObjectParameter("userUname", typeof(string));
    
            var userPwordParameter = userPword != null ?
                new ObjectParameter("userPword", userPword) :
                new ObjectParameter("userPword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_new_useraccount", userUnameParameter, userPwordParameter);
        }
    }
}
